### PR TITLE
Download asm.js game files

### PR DESCRIPTION
**Pull request by sparr**
The goal here is to add support for downloading asm.js games, the ones that play directly in the browser, like Osmos, Zen Bound 2, FTL, etc. I'm stuck on how to produce the HMAC and other auth parameters for the CDN download URLs.

e.g. I want https://cdn.humble.com/humblebundle/asm_js/osmos_asm/osmos-1414005570.js but I need to request https://cdn.humble.com/humblebundle/asm_js/osmos_asm/osmos-1414005570.js?t=st=1722099999~exp=1722199999~hmac=deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef

PS: the exception logging is also a placeholder; I'd clean that back up to something more readable once this is working.

### CODE REVIEW

**Comment by sparr** [comment]
Latest push fixes the HMAC problem, the hydrated URLs are available in a script in another page which can be requested with the session credentials.

Now I have a weird problem... For `Humble Bundle for Android/Osmos` it successfully downloads two of the five files, but the other three files produce really weird progress bar output then a failure:

```
Downloading: /mnt/volume_nyc3_01/HumbleBundleDownload/Humble Bundle for Android/Osmos/osmos_asm/osmos.js
        276% [==========================================================================================================================================]       276% [==========================================================================================================================================]       276% [==========================================================================================================================================]       276% [==========================================================================================================================================]       278% [===========================================================================================================================================]      278%

[CUT HUNDREDS OF LINES OF PROGRESS INCREASING 2% AT A TIME] 

[==================================================================================================================================================444% [==================================================================================================================================================444% [==================================================================================================================================================444% [==================================================================================================================================================444% [==================================================================================================================================================446% [==================================================================================================================================================446% [==================================================================================================================================================446% [===============================================================================================================================================================================================================================]
Failed to download file /mnt/volume_nyc3_01/HumbleBundleDownload/Humble Bundle for Android/Osmos/osmos_asm/osmos.js
```

Troubleshooting continues...

**Comment by sparr** [comment]
AHA! Some of the files have `content-length` of less than the total size of the file?!

Temporarily replaced the progress bar with text output.

As of right now, this successfully downloads Osmos from five different bundles, but fails on every other asmjs game so clearly I've made some osmos-specific assumption while I used it for testing. I'll pick another game to look for commonalities and try to make this more generic and effective.

**Comment by sparr** [comment]
Latest push might have fixed the progress bar. Also is successfully downloading html and js and data for many asm.js games across many bundles.

The html file download doesn't provide a Last-Modified header, which is proving tricky to deal with for caching.

I did some refactoring, but still need a lot of cleanup.

**Comment by sparr** [comment]
I have confirmed that if I edit the html file to replace the CDN urls for the asm.js files with just their filenames, then start up an http server in the directory, I can request the html file and click the play button and it will successfully launch a game!

image

**Comment by sparr** [comment]
This PR is technically functional now, so I'm going to mark it as no longer a draft and hope that gets attention for a review. I'd like some refactor and other style suggestions from @xtream1101 before I try to move this towards mergeability. Also some insight on the preferred solution for caching and editing the html files.

**Comment by sparr** [comment]
Here are the 45 downloads that I got with the current version of this PR:
```
FTL - Faster Than Light/FTL - Faster than Light/ftlfasterthanlight/ftlfasterthanlight.html
Humble Bundle - PC and Android 8/AaaaaAAaaaAAAaaAAAAaAAAAA for the Awesome/aaaaaa_fortheawesome/aaaaaa_fortheawesome.html
Humble Bundle - PC and Android 8/Jack Lumber/jacklumber/jacklumber.html
Humble Bundle for Android 2/Zen Bound 2/zenbound2/zenbound2.html
Humble Bundle for Android 3/Osmos/osmos_asm/osmos_asm.html
Humble Bundle for Android 4/Zen Bound 2/zenbound2/zenbound2.html
Humble Bundle for Android/Osmos/osmos_asm/osmos_asm.html
Humble Bundle with Android 5/Super Hexagon/superhexagon/superhexagon.html
Humble Indie Bundle 2/Osmos/osmos_asm/osmos_asm.html
Humble Indie Bundle 3/Osmos/osmos_asm/osmos_asm.html
Humble Indie Bundle 6/Dustforce DX/dustforce/dustforce.html
Humble Indie Bundle 9/FTL - Faster than Light/ftlfasterthanlight/ftlfasterthanlight.html
Humble Mozilla Bundle - Powered by asm.js/AaaaaAAaaaAAAaaAAAAaAAAAA for the Awesome/aaaaaa_fortheawesome/aaaaaa_fortheawesome.html
Humble Mozilla Bundle - Powered by asm.js/Democracy 3/democracy3/democracy3.html
Humble Mozilla Bundle - Powered by asm.js/Dustforce DX/dustforce/dustforce.html
Humble Mozilla Bundle - Powered by asm.js/FTL - Faster than Light/ftlfasterthanlight/ftlfasterthanlight.html
Humble Mozilla Bundle - Powered by asm.js/Jack Lumber/jacklumber/jacklumber.html
Humble Mozilla Bundle - Powered by asm.js/Osmos/osmos_asm/osmos_asm.html
Humble Mozilla Bundle - Powered by asm.js/Super Hexagon/superhexagon/superhexagon.html
Humble Mozilla Bundle - Powered by asm.js/Voxatron/voxatron/shell.html
Humble Mozilla Bundle - Powered by asm.js/Voxatron/voxatron/voxatron.html
Humble Mozilla Bundle - Powered by asm.js/Zen Bound 2/zenbound2/zenbound2.html
Humble NEOGEO Encore Bundle/BLAZING STAR/blazingstar/blazingstar.html
Humble NEOGEO Encore Bundle/FATAL FURY SPECIAL/fatalfury_special/fatalfury_special.html
Humble NEOGEO Encore Bundle/GAROU - MARK OF THE WOLVES/garou_markofthewolves/garou_markofthewolves.html
Humble NEOGEO Encore Bundle/IRONCLAD/ironclad/ironclad.html
Humble NEOGEO Encore Bundle/KING OF THE MONSTERS/kingofthemonsters/kingofthemonsters.html
Humble NEOGEO Encore Bundle/METAL SLUG 2/metalslug2/metalslug2.html
Humble NEOGEO Encore Bundle/METAL SLUG 3/metalslug3/metalslug3.html
Humble NEOGEO Encore Bundle/METAL SLUG X/metalslugx/metalslugx.html
Humble NEOGEO Encore Bundle/METAL SLUG/metalslug/metalslug.html
Humble NEOGEO Encore Bundle/NEO TURF MASTERS/neoturfmasters/neoturfmasters.html
Humble NEOGEO Encore Bundle/PULSTAR/pulstar_neogeo/pulstar_neogeo.html
Humble NEOGEO Encore Bundle/REAL BOUT FATAL FURY 2 - THE NEWCOMERS/realboutfatalfury2_thenewcomers/realboutfatalfury2_thenewcomers.html
Humble NEOGEO Encore Bundle/SAMURAI SHODOWN II/samuraishodown2/samuraishodown2.html
Humble NEOGEO Encore Bundle/SAMURAI SHODOWN V SPECIAL/samuraishodown5_special/samuraishodown5_special.html
Humble NEOGEO Encore Bundle/SENGOKU 3/sengoku3/sengoku3.html
Humble NEOGEO Encore Bundle/SHOCK TROOPERS - 2nd SQUAD/shocktroopers_2ndsquad/shocktroopers_2ndsquad.html
Humble NEOGEO Encore Bundle/SHOCK TROOPERS/shocktroopers/shocktroopers.html
Humble NEOGEO Encore Bundle/THE KING OF FIGHTERS 2000/thekingoffighters_2000/thekingoffighters_2000.html
Humble NEOGEO Encore Bundle/THE KING OF FIGHTERS 2002/thekingoffighters_2002_base/thekingoffighters_2002_base.html
Humble NEOGEO Encore Bundle/THE LAST BLADE/thelastblade/thelastblade.html
Humble NEOGEO Encore Bundle/TWINKLE STAR SPRITES/twinklestarsprites/twinklestarsprites.html
Humble Voxatron Debut/Voxatron/voxatron/shell.html
Humble Voxatron Debut/Voxatron/voxatron/voxatron.html
```

Deduplicating the list, there are 30 unique games:
```
aaaaaa_fortheawesome
blazingstar
democracy3
dustforce
fatalfury_special
ftlfasterthanlight
garou_markofthewolves
ironclad
jacklumber
kingofthemonsters
metalslug
metalslug2
metalslug3
metalslugx
neoturfmasters
osmos_asm
pulstar_neogeo
realboutfatalfury2_thenewcomers
samuraishodown2
samuraishodown5_special
sengoku3
shocktroopers
shocktroopers_2ndsquad
superhexagon
thekingoffighters_2000
thekingoffighters_2002_base
thelastblade
twinklestarsprites
voxatron
zenbound2
```

**Comment by xtream1101** [comment]
@sparr I was not aware of these types of games on the site (I do not have any in my account 😞)

I have made a few recent updates which seems to have created a few conflicts with this branch. You can resolve them then also use https://pre-commit.com/ locally to handle code formatting/linting. Just install pre-commit then in the repo run `pre-commit install` since I added a config for it it will run on your next commit.

As for the caching issue that's an interesting one. A simple way to handle a case of a missing last-modified header would be to just use the current timestamp on download. This way on a normal run it should not re-download, but if you use `--update` it will always re-download just to be safe. Thoughts?

I can help with ways to edit the html file to fix the links too if you still need too.

**Comment by sparr** [comment]
I'll run pre-commit, and that caching solution seems fine.

As to editing the file... I think making a second copy is the best option, especially since we probably need the original URLs in the file to use on later runs to check if the target files have changed.

**Comment by sparr** [comment]
Merge conflicts fixed. Linter/Formatter run. url_last_modified set to the current time if it's missing. foo.html duplicated as foo.local.html with the manifest URLs changed to the local paths.

Confirmed this still works with a `python3 -m http.server 8080` in the output directory to serve the files.

**Pull request merged**
